# Site settings
title: Genomics of Regulatory RNA
email: selene.fernandez.valverde@gmail.com
description: About #
baseurl: "/lab-site" # the subpath of your site, e.g. /blog/
url: "http://liz-fernandez.github.io/lab-site/" # the base hostname & protocol for your site
twitter_username: SelFdz
github_username:  liz-fernandez

# Build settings
markdown: kramdown
