# Site settings
title: Ion
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/lab-site" # the subpath of your site, e.g. /blog/
url: "http://liz-fernandez.github.io/lab-site/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
